name: GitHub Actions Demo
run-name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/${{ github.repository }}.git .
      - run: ls
      - run: mkdir -p tests
      - run: echo "Creating test directory"
      - run: ls
      - run: cp examples/Русский_забор.cpp tests/
      - run: cp examples/связный_список.cpp tests/
      - run: cp examples/Слава_Руси.cpp tests/
      - run: cp examples/Сортировочка_2.cpp tests/
      - run: cp examples/Сортировочка.cpp tests/
      - run: cp header/Ве_крест_крест.h tests/
      - run: mkdir -p tests/cpp
      - run: cp header/cpp/sort_static.cpp tests/cpp
      - run: echo "Creating test header"
      - run: cd tests && echo "Moving test directory" && g++ Русский_забор.cpp && g++ связный_список.cpp && g++ Слава_Руси.cpp && g++ Сортировочка_2.cpp && g++ Сортировочка.cpp && echo "all complete" && cd .. && rm -r tests